stages:
    - build

build-job:
    image: haskell:9.4.7-slim-buster
    stage: build
    script:
        - apt update -y && apt install file -y
        - cabal update
        - cabal build

    artifacts:
        untracked: false
        when: on_success
        expire_in: 7 days
        paths: 
            - dist-newstyle/build/x86_64-linux/ghc-9.4.7/hephaestus-1.0.0.0/x/hephaestus/build/hephaestus