stages:
    - build
    - publish

build-cabal:
    image: haskell:9.4.7-slim-buster
    stage: build

    cache:
      - key: hephaestus
        paths:
          - /root/.cabal/

    script:
        - apt update -y && apt install libmagic-dev -y
        - cabal update
        - cabal build
        - cp dist-newstyle/build/x86_64-linux/ghc-9.4.7/hephaestus-1.0.0.0/x/hephaestus/build/hephaestus/hephaestus hephaestus

    artifacts:
        untracked: false
        when: on_success
        expire_in: 7 days
        paths: 
            - hephaestus

build-container:
  image: 
    name: docker:24.0.5
  stage: publish
  dependencies: 
    - build-cabal
  services:
    - docker:24.0.5-dind
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    FQ_IMAGE_NAME: "$CI_REGISTRY_IMAGE/test"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $FQ_IMAGE_NAME
    - docker push $FQ_IMAGE_NAME